// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace raauu
{
    internal sealed partial class Vsix
    {
        public const string Id = "raauu.67684396-6aac-41fb-bf2e-2df8ffae7903";
        public const string Name = "Randomize and Add Useless Usings";
        public const string Description = @"Randomize and Add Useless Usings is a Visual Studio extension that adds a command which does the opposite of the Remove and Sort Usings command in C# code contexts.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "lettucemode";
        public const string Tags = "add,randomize,useless,usings";
    }
}
