// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace raauu
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string raauuString = "19c81aa0-d5b3-4ade-b931-2ed9ef16b359";
        public static Guid raauu = new Guid(raauuString);

        public const string AutoLoadString = "f4e31bf9-765a-4be5-885e-548d1fec6897";
        public static Guid AutoLoad = new Guid(AutoLoadString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int raauuCommand = 0x0100;
    }
}